### ISSUE TITLE
[Dialog] Issue

### ISSUE THREAD

**Issue by KOFI-GYIMAH** [radix-ui/themes#103]
Property 'className' does not exist on type 'DialogPortalProps'.

**Comment by kevinmitch14** [comment]
It would be very helpful if you share more information such as a code example

**Comment by kevinmitch14** [comment]
If you are referring to `<Dialog.Portal>` from [Radix Primitives](https://www.radix-ui.com/primitives/docs/components/dialog#portal), this does not accept className as a prop. 

It only accepts: forceMount, container & children which can be seen [here](https://github.com/radix-ui/primitives/blob/c31c97274ff357aea99afe6c01c1c8c58b6356e0/packages/react/dialog/src/Dialog.tsx#L132-L143).

**Comment by AdiRishi** [comment]
Just ran into the same thing. Was using the Shadcn UI Dialog component and it had code like this
```ts
const DialogPortal = ({ className, ...props }: DialogPrimitive.DialogPortalProps) => (
  <DialogPrimitive.Portal className={cn(className)} {...props} />
);
DialogPortal.displayName = DialogPrimitive.Portal.displayName;
```

This code worked fine in `@radix-ui/react-dialog` `1.0.4` but breaks in `1.0.5` with this error
```
error TS2339: Property 'className' does not exist on type 'DialogPortalProps'.
error TS2322: Type '{ children?: ReactNode; container?: HTMLElement | null | undefined; forceMount?: true | undefined; className: string; }' is not assignable to type 'IntrinsicAttributes & DialogPortalProps'
```

With that being said, it doesn't actually look like `<DialogPortal>` was being given any classname values, so simply removing it should fix the issue. But just mentioning it here for sake of noting breaking changes.

See https://github.com/shadcn-ui/ui/issues/1624 for the issue on shadcn side
